name = "shorter-director"
main = "dist/index.mjs"

compatibility_date = "2022-07-01"
compatibility_flags = []

workers_dev = false
route = "https://wffl.link/*"

[build]
command = "yarn build"

[miniflare]
kv_persist = true
cache_persist = true
