on:
  push:
    branches:
      - main

jobs:
  director:
    name: Director
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: director/.node-version
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: yarn install --frozen-lockfile --immutable
      - run: yarn workspace director deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
